# Generated by Django 4.0.3 on 2022-05-03 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_suppliers'),
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='In stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(default=0.0, verbose_name='Sell Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.suppliers', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(default=0.0, verbose_name='Unitary Price'),
        ),
    ]
