# Generated by Django 4.0.3 on 2022-05-03 03:52

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_user_is_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=255, verbose_name='Phone')),
                ('cellphone', models.CharField(blank=True, default='', max_length=255, verbose_name='Cellphone')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('is_active', models.BooleanField(default=True, verbose_name="It's Active")),
                ('nit', models.CharField(blank=True, default='', max_length=255, verbose_name='Nit')),
                ('website', models.CharField(blank=True, default='', max_length=255, verbose_name='Website')),
            ],
        ),
    ]
